version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - app
    ports:
      - "80:80"
    links:
      - app:app
    volumes:
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
      - fiveman_public:/var/www/public:ro
      - fiveman_book:/var/www/book:ro
  app:
    build: .
    environment:
      - STANDALONE=false
    ports:
      - "3002"
    volumes:
      - fiveman_public:/usr/src/app/public
      - fiveman_book:/usr/src/app/book
volumes:
  fiveman_public:
  fiveman_book:
